### PR TITLE
Adds generics support and columns to PrestoResponse

### PR DESCRIPTION
**Pull request by MattySheikh**
* Supports Generics in `data` and `warnings` properties of `PrestoResponse`
* Introduces `columns` support in `PrestoResponse`
* Version bump to 1.1.7

### CODE REVIEW

**Comment by MattySheikh** [comment]
@joelgarciajr84 whenever you get the chance to review. Apologies if this double pinged you, not sure what notifications Github sends.

**Comment by joelgarciajr84** [comment]
Hi @MattySheikh  sorry for the delay!
PR Approved and merged, thanks for the contribution!

**Comment by MattySheikh** [comment]
Thank you, Joel! Any chance you could publish the new version whenever you get the chance?

**Comment by joelgarciajr84** [comment]
> Thank you, Joel! Any chance you could publish the new version whenever you get the chance?

Hi Mattty, lib updated on NPM, thanks for the PR.

**Pull request merged**
